name: tourist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ######### Firebase Package #########
  firebase_auth: ^3.3.7
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.8
  ######### Firebase Package #########
  #
  ########################################
  intl: ^0.17.0
  sizer: ^2.0.15
  min_id: ^1.1.0
  qr_flutter: ^4.0.0
  charts_flutter: ^0.12.0
  image_picker: ^0.8.5
  url_launcher: ^6.0.20
  flutter_bloc: ^7.3.3
  buildcondition: ^0.0.4
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.13
  translator: ^0.1.7

  ########################################
  #
  ######## Native Splash Plugin ########
  flutter_native_splash: ^2.1.1
flutter_native_splash:
  background_image: "assets/images/splash/splash.png"
  android_gravity: center
  ios_content_mode: center
  android_12:
  android: true
  ios: true
  ######## Native Splash Plugin ########
  #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/Tourista.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  # example:
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
