// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBThOdLetRSzgsa320QNGiePqZjUV2yFxI',
    appId: '1:236422918539:web:c84e67fefe14b8ca91ff8e',
    messagingSenderId: '236422918539',
    projectId: 'tourism-45327',
    authDomain: 'tourism-45327.firebaseapp.com',
    databaseURL: 'https://tourism-45327-default-rtdb.firebaseio.com',
    storageBucket: 'tourism-45327.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfzlKh6PdF0QhlfVfrQQ4tk-GwHGGpWug',
    appId: '1:236422918539:android:54b82bde979b7b0e91ff8e',
    messagingSenderId: '236422918539',
    projectId: 'tourism-45327',
    databaseURL: 'https://tourism-45327-default-rtdb.firebaseio.com',
    storageBucket: 'tourism-45327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pIotoODS5NhMyGAwi23ejjb3x2M9s1Y',
    appId: '1:236422918539:ios:0b0c421ee5b95d5291ff8e',
    messagingSenderId: '236422918539',
    projectId: 'tourism-45327',
    databaseURL: 'https://tourism-45327-default-rtdb.firebaseio.com',
    storageBucket: 'tourism-45327.appspot.com',
    androidClientId: '236422918539-6sqkakpqasqudsskq0vbvp2ehj4hpaie.apps.googleusercontent.com',
    iosClientId: '236422918539-6rhoi1onq1q1b00g0kg37q4v9piqkb4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourist',
  );
}
